/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {0, 2, 5};
static const casadi_int casadi_s1[3] = {1, 3, 6};
static const casadi_int casadi_s2[3] = {0, 3, 5};
static const casadi_int casadi_s3[3] = {2, 4, 7};
static const casadi_int casadi_s4[19] = {8, 8, 0, 0, 0, 0, 0, 0, 3, 5, 8, 5, 6, 7, 5, 7, 5, 6, 7};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s7[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s10[16] = {8, 5, 0, 2, 5, 6, 7, 8, 5, 6, 5, 6, 7, 3, 6, 7};
static const casadi_int casadi_s11[8] = {0, 5, 0, 0, 0, 0, 0, 0};

/* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess:(i0[6],i1[2],i2[5],i3[],i4)->(o0[5],o1[8x5,8nz],o2[8x8,8nz],o3[0x5],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, *w20=w+20, *w21=w+28, w22, w23, w24, *w27=w+37, *w28=w+40, *w30=w+43, *w31=w+45, *w34=w+47, w35, w36, w37, *w39=w+55;
  /* #0: @0 = 0.28 */
  w0 = 2.8000000000000003e-001;
  /* #1: @1 = 0.05 */
  w1 = 5.0000000000000003e-002;
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = (@1*@2) */
  w3  = (w1*w2);
  /* #4: @0 = (@0-@3) */
  w0 -= w3;
  /* #5: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: @5 = 0.006 */
  w5 = 6.0000000000000001e-003;
  /* #8: @6 = (@5*@2) */
  w6  = (w5*w2);
  /* #9: @7 = (@6*@2) */
  w7  = (w6*w2);
  /* #10: @4 = (@4-@7) */
  w4 -= w7;
  /* #11: @7 = 0.011 */
  w7 = 1.0999999999999999e-002;
  /* #12: @8 = 5 */
  w8 = 5.;
  /* #13: @9 = (@8*@2) */
  w9  = (w8*w2);
  /* #14: @9 = tanh(@9) */
  w9 = tanh( w9 );
  /* #15: @10 = (@7*@9) */
  w10  = (w7*w9);
  /* #16: @4 = (@4-@10) */
  w4 -= w10;
  /* #17: @10 = input[4][0] */
  w10 = arg[4] ? arg[4][0] : 0;
  /* #18: @11 = (@4/@10) */
  w11  = (w4/w10);
  /* #19: output[0][0] = @11 */
  if (res[0]) res[0][0] = w11;
  /* #20: @11 = 15.5 */
  w11 = 1.5500000000000000e+001;
  /* #21: @12 = (@11*@2) */
  w12  = (w11*w2);
  /* #22: @13 = (@12*@2) */
  w13  = (w12*w2);
  /* #23: @14 = input[0][5] */
  w14 = arg[0] ? arg[0][5] : 0;
  /* #24: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #25: @16 = 0.5 */
  w16 = 5.0000000000000000e-001;
  /* #26: @17 = (@16*@14) */
  w17  = (w16*w14);
  /* #27: @18 = sin(@17) */
  w18 = sin( w17 );
  /* #28: @19 = (@4*@18) */
  w19  = (w4*w18);
  /* #29: @19 = (@19/@10) */
  w19 /= w10;
  /* #30: @15 = (@15+@19) */
  w15 += w19;
  /* #31: output[0][1] = @15 */
  if (res[0]) res[0][1] = w15;
  /* #32: @15 = input[0][1] */
  w15 = arg[0] ? arg[0][1] : 0;
  /* #33: output[0][2] = @15 */
  if (res[0]) res[0][2] = w15;
  /* #34: output[0][3] = @3 */
  if (res[0]) res[0][3] = w3;
  /* #35: output[0][4] = @14 */
  if (res[0]) res[0][4] = w14;
  /* #36: @20 = zeros(8x5,8nz) */
  casadi_clear(w20, 8);
  /* #37: @21 = ones(8x1,6nz) */
  casadi_fill(w21, 6, 1.);
  /* #38: {NULL, NULL, NULL, @15, NULL, @19, NULL, NULL} = vertsplit(@21) */
  w15 = w21[3];
  w19 = w21[5];
  /* #39: @22 = (@5*@19) */
  w22  = (w5*w19);
  /* #40: @22 = (@2*@22) */
  w22  = (w2*w22);
  /* #41: @23 = (@6*@19) */
  w23  = (w6*w19);
  /* #42: @22 = (@22+@23) */
  w22 += w23;
  /* #43: @22 = (-@22) */
  w22 = (- w22 );
  /* #44: @23 = (@1*@19) */
  w23  = (w1*w19);
  /* #45: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #46: @22 = (@22-@23) */
  w22 -= w23;
  /* #47: @23 = 1 */
  w23 = 1.;
  /* #48: @24 = sq(@9) */
  w24 = casadi_sq( w9 );
  /* #49: @23 = (@23-@24) */
  w23 -= w24;
  /* #50: @24 = (@8*@19) */
  w24  = (w8*w19);
  /* #51: @23 = (@23*@24) */
  w23 *= w24;
  /* #52: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #53: @22 = (@22-@23) */
  w22 -= w23;
  /* #54: @23 = (@22/@10) */
  w23  = (w22/w10);
  /* #55: @24 = (@11*@19) */
  w24  = (w11*w19);
  /* #56: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #57: @19 = (@12*@19) */
  w19  = (w12*w19);
  /* #58: @24 = (@24+@19) */
  w24 += w19;
  /* #59: @24 = (@14*@24) */
  w24  = (w14*w24);
  /* #60: @22 = (@18*@22) */
  w22  = (w18*w22);
  /* #61: @22 = (@22/@10) */
  w22 /= w10;
  /* #62: @24 = (@24+@22) */
  w24 += w22;
  /* #63: @25 = 00 */
  /* #64: @26 = 00 */
  /* #65: @27 = vertcat(@23, @24, @15, @25, @26) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w24;
  *rr++ = w15;
  /* #66: @28 = @27[:3] */
  for (rr=w28, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #67: (@20[0, 2, 5] = @28) */
  for (cii=casadi_s0, rr=w20, ss=w28; cii!=casadi_s0+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #68: @23 = ones(8x1,1nz) */
  w23 = 1.;
  /* #69: {NULL, NULL, NULL, NULL, NULL, NULL, @24, NULL} = vertsplit(@23) */
  w24 = w23;
  /* #70: @23 = (@0*@24) */
  w23  = (w0*w24);
  /* #71: @15 = (@23/@10) */
  w15  = (w23/w10);
  /* #72: @23 = (@18*@23) */
  w23  = (w18*w23);
  /* #73: @23 = (@23/@10) */
  w23 /= w10;
  /* #74: @25 = 00 */
  /* #75: @26 = 00 */
  /* #76: @28 = vertcat(@15, @23, @25, @24, @26) */
  rr=w28;
  *rr++ = w15;
  *rr++ = w23;
  *rr++ = w24;
  /* #77: @27 = @28[:3] */
  for (rr=w27, ss=w28+0; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #78: (@20[1, 3, 6] = @27) */
  for (cii=casadi_s1, rr=w20, ss=w27; cii!=casadi_s1+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #79: @25 = 00 */
  /* #80: @15 = ones(8x1,1nz) */
  w15 = 1.;
  /* #81: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @23} = vertsplit(@15) */
  w23 = w15;
  /* #82: @13 = (@13*@23) */
  w13 *= w23;
  /* #83: @15 = cos(@17) */
  w15 = cos( w17 );
  /* #84: @24 = (@16*@23) */
  w24  = (w16*w23);
  /* #85: @15 = (@15*@24) */
  w15 *= w24;
  /* #86: @15 = (@4*@15) */
  w15  = (w4*w15);
  /* #87: @15 = (@15/@10) */
  w15 /= w10;
  /* #88: @13 = (@13+@15) */
  w13 += w15;
  /* #89: @26 = 00 */
  /* #90: @29 = 00 */
  /* #91: @30 = vertcat(@25, @13, @26, @29, @23) */
  rr=w30;
  *rr++ = w13;
  *rr++ = w23;
  /* #92: @31 = @30[:2] */
  for (rr=w31, ss=w30+0; ss!=w30+2; ss+=1) *rr++ = *ss;
  /* #93: (@20[4:10:3] = @31) */
  for (rr=w20+4, ss=w31; rr!=w20+10; rr+=3) *rr = *ss++;
  /* #94: output[1][0] = @20 */
  casadi_copy(w20, 8, res[1]);
  /* #95: @20 = zeros(8x8,8nz) */
  casadi_clear(w20, 8);
  /* #96: @25 = 00 */
  /* #97: @26 = 00 */
  /* #98: @29 = 00 */
  /* #99: @32 = 00 */
  /* #100: @33 = 00 */
  /* #101: @34 = input[2][0] */
  casadi_copy(arg[2], 5, w34);
  /* #102: {@13, @23, NULL, NULL, NULL} = vertsplit(@34) */
  w13 = w34[0];
  w23 = w34[1];
  /* #103: @14 = (@14*@23) */
  w14 *= w23;
  /* #104: @21 = ones(8x1,6nz) */
  casadi_fill(w21, 6, 1.);
  /* #105: {NULL, NULL, NULL, NULL, NULL, @15, NULL, NULL} = vertsplit(@21) */
  w15 = w21[5];
  /* #106: @24 = (@11*@15) */
  w24  = (w11*w15);
  /* #107: @22 = (@14*@24) */
  w22  = (w14*w24);
  /* #108: @14 = (@14*@15) */
  w14 *= w15;
  /* #109: @14 = (@11*@14) */
  w14  = (w11*w14);
  /* #110: @22 = (@22+@14) */
  w22 += w14;
  /* #111: @14 = (@23/@10) */
  w14  = (w23/w10);
  /* #112: @18 = (@18*@14) */
  w18 *= w14;
  /* #113: @13 = (@13/@10) */
  w13 /= w10;
  /* #114: @18 = (@18+@13) */
  w18 += w13;
  /* #115: @13 = (@7*@18) */
  w13  = (w7*w18);
  /* #116: @10 = (2.*@9) */
  w10 = (2.* w9 );
  /* #117: @19 = 1 */
  w19 = 1.;
  /* #118: @35 = sq(@9) */
  w35 = casadi_sq( w9 );
  /* #119: @19 = (@19-@35) */
  w19 -= w35;
  /* #120: @35 = (@8*@15) */
  w35  = (w8*w15);
  /* #121: @19 = (@19*@35) */
  w19 *= w35;
  /* #122: @10 = (@10*@19) */
  w10 *= w19;
  /* #123: @13 = (@13*@10) */
  w13 *= w10;
  /* #124: @13 = (@8*@13) */
  w13  = (w8*w13);
  /* #125: @22 = (@22+@13) */
  w22 += w13;
  /* #126: @13 = (@5*@15) */
  w13  = (w5*w15);
  /* #127: @10 = (@18*@13) */
  w10  = (w18*w13);
  /* #128: @22 = (@22-@10) */
  w22 -= w10;
  /* #129: @10 = (@18*@15) */
  w10  = (w18*w15);
  /* #130: @10 = (@5*@10) */
  w10  = (w5*w10);
  /* #131: @22 = (@22-@10) */
  w22 -= w10;
  /* #132: @10 = (@1*@15) */
  w10  = (w1*w15);
  /* #133: @35 = (@18*@10) */
  w35  = (w18*w10);
  /* #134: @35 = (-@35) */
  w35 = (- w35 );
  /* #135: @36 = cos(@17) */
  w36 = cos( w17 );
  /* #136: @13 = (@2*@13) */
  w13  = (w2*w13);
  /* #137: @37 = (@6*@15) */
  w37  = (w6*w15);
  /* #138: @13 = (@13+@37) */
  w13 += w37;
  /* #139: @13 = (-@13) */
  w13 = (- w13 );
  /* #140: @10 = (@3*@10) */
  w10  = (w3*w10);
  /* #141: @13 = (@13-@10) */
  w13 -= w10;
  /* #142: @19 = (@7*@19) */
  w19  = (w7*w19);
  /* #143: @13 = (@13-@19) */
  w13 -= w19;
  /* #144: @13 = (@14*@13) */
  w13  = (w14*w13);
  /* #145: @13 = (@36*@13) */
  w13  = (w36*w13);
  /* #146: @13 = (@16*@13) */
  w13  = (w16*w13);
  /* #147: @24 = (@2*@24) */
  w24  = (w2*w24);
  /* #148: @15 = (@12*@15) */
  w15  = (w12*w15);
  /* #149: @24 = (@24+@15) */
  w24 += w15;
  /* #150: @24 = (@23*@24) */
  w24  = (w23*w24);
  /* #151: @13 = (@13+@24) */
  w13 += w24;
  /* #152: @27 = vertcat(@25, @26, @29, @32, @33, @22, @35, @13) */
  rr=w27;
  *rr++ = w22;
  *rr++ = w35;
  *rr++ = w13;
  /* #153: @28 = @27[:3] */
  for (rr=w28, ss=w27+0; ss!=w27+3; ss+=1) *rr++ = *ss;
  /* #154: (@20[0, 3, 5] = @28) */
  for (cii=casadi_s2, rr=w20, ss=w28; cii!=casadi_s2+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #155: @25 = 00 */
  /* #156: @26 = 00 */
  /* #157: @29 = 00 */
  /* #158: @32 = 00 */
  /* #159: @33 = 00 */
  /* #160: @22 = ones(8x1,1nz) */
  w22 = 1.;
  /* #161: {NULL, NULL, NULL, NULL, NULL, NULL, @35, NULL} = vertsplit(@22) */
  w35 = w22;
  /* #162: @18 = (@18*@35) */
  w18 *= w35;
  /* #163: @18 = (@1*@18) */
  w18  = (w1*w18);
  /* #164: @18 = (-@18) */
  w18 = (- w18 );
  /* #165: @38 = 00 */
  /* #166: @35 = (@0*@35) */
  w35  = (w0*w35);
  /* #167: @35 = (@14*@35) */
  w35  = (w14*w35);
  /* #168: @36 = (@36*@35) */
  w36 *= w35;
  /* #169: @36 = (@16*@36) */
  w36  = (w16*w36);
  /* #170: @31 = vertcat(@25, @26, @29, @32, @33, @18, @38, @36) */
  rr=w31;
  *rr++ = w18;
  *rr++ = w36;
  /* #171: @30 = @31[:2] */
  for (rr=w30, ss=w31+0; ss!=w31+2; ss+=1) *rr++ = *ss;
  /* #172: (@20[1:11:5] = @30) */
  for (rr=w20+1, ss=w30; rr!=w20+11; rr+=5) *rr = *ss++;
  /* #173: @25 = 00 */
  /* #174: @26 = 00 */
  /* #175: @29 = 00 */
  /* #176: @32 = 00 */
  /* #177: @33 = 00 */
  /* #178: @18 = ones(8x1,1nz) */
  w18 = 1.;
  /* #179: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @36} = vertsplit(@18) */
  w36 = w18;
  /* #180: @23 = (@23*@36) */
  w23 *= w36;
  /* #181: @12 = (@12*@23) */
  w12 *= w23;
  /* #182: @23 = (@2*@23) */
  w23  = (w2*w23);
  /* #183: @11 = (@11*@23) */
  w11 *= w23;
  /* #184: @12 = (@12+@11) */
  w12 += w11;
  /* #185: @11 = 1 */
  w11 = 1.;
  /* #186: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #187: @11 = (@11-@9) */
  w11 -= w9;
  /* #188: @9 = cos(@17) */
  w9 = cos( w17 );
  /* #189: @36 = (@16*@36) */
  w36  = (w16*w36);
  /* #190: @9 = (@9*@36) */
  w9 *= w36;
  /* #191: @9 = (@14*@9) */
  w9  = (w14*w9);
  /* #192: @7 = (@7*@9) */
  w7 *= w9;
  /* #193: @11 = (@11*@7) */
  w11 *= w7;
  /* #194: @8 = (@8*@11) */
  w8 *= w11;
  /* #195: @12 = (@12-@8) */
  w12 -= w8;
  /* #196: @6 = (@6*@9) */
  w6 *= w9;
  /* #197: @12 = (@12-@6) */
  w12 -= w6;
  /* #198: @2 = (@2*@9) */
  w2 *= w9;
  /* #199: @5 = (@5*@2) */
  w5 *= w2;
  /* #200: @12 = (@12-@5) */
  w12 -= w5;
  /* #201: @3 = (@3*@9) */
  w3 *= w9;
  /* #202: @1 = (@1*@3) */
  w1 *= w3;
  /* #203: @12 = (@12-@1) */
  w12 -= w1;
  /* #204: @0 = (@0*@9) */
  w0 *= w9;
  /* #205: @4 = (@4*@14) */
  w4 *= w14;
  /* #206: @17 = sin(@17) */
  w17 = sin( w17 );
  /* #207: @17 = (@17*@36) */
  w17 *= w36;
  /* #208: @4 = (@4*@17) */
  w4 *= w17;
  /* #209: @16 = (@16*@4) */
  w16 *= w4;
  /* #210: @16 = (-@16) */
  w16 = (- w16 );
  /* #211: @28 = vertcat(@25, @26, @29, @32, @33, @12, @0, @16) */
  rr=w28;
  *rr++ = w12;
  *rr++ = w0;
  *rr++ = w16;
  /* #212: @27 = @28[:3] */
  for (rr=w27, ss=w28+0; ss!=w28+3; ss+=1) *rr++ = *ss;
  /* #213: (@20[2, 4, 7] = @27) */
  for (cii=casadi_s3, rr=w20, ss=w27; cii!=casadi_s3+3; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #214: @39 = @20' */
  casadi_trans(w20,casadi_s4, w39, casadi_s4, iw);
  /* #215: output[2][0] = @39 */
  casadi_copy(w39, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s10;
    case 2: return casadi_s4;
    case 3: return casadi_s11;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 13;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 63;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
