/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Spatialbicycle_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* Spatialbicycle_model_constr_h_fun:(i0[6],i1[2],i2[],i3)->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = 0.28 */
  w0 = 2.8000000000000003e-001;
  /* #1: @1 = 0.05 */
  w1 = 5.0000000000000003e-002;
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @1 = (@1*@2) */
  w1 *= w2;
  /* #4: @0 = (@0-@1) */
  w0 -= w1;
  /* #5: @1 = input[0][4] */
  w1 = arg[0] ? arg[0][4] : 0;
  /* #6: @0 = (@0*@1) */
  w0 *= w1;
  /* #7: @3 = 0.006 */
  w3 = 6.0000000000000001e-003;
  /* #8: @3 = (@3*@2) */
  w3 *= w2;
  /* #9: @3 = (@3*@2) */
  w3 *= w2;
  /* #10: @0 = (@0-@3) */
  w0 -= w3;
  /* #11: @3 = 0.011 */
  w3 = 1.0999999999999999e-002;
  /* #12: @4 = 5 */
  w4 = 5.;
  /* #13: @4 = (@4*@2) */
  w4 *= w2;
  /* #14: @4 = tanh(@4) */
  w4 = tanh( w4 );
  /* #15: @3 = (@3*@4) */
  w3 *= w4;
  /* #16: @0 = (@0-@3) */
  w0 -= w3;
  /* #17: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #18: @4 = (@0/@3) */
  w4  = (w0/w3);
  /* #19: output[0][0] = @4 */
  if (res[0]) res[0][0] = w4;
  /* #20: @4 = 15.5 */
  w4 = 1.5500000000000000e+001;
  /* #21: @4 = (@4*@2) */
  w4 *= w2;
  /* #22: @4 = (@4*@2) */
  w4 *= w2;
  /* #23: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #24: @4 = (@4*@2) */
  w4 *= w2;
  /* #25: @5 = 0.5 */
  w5 = 5.0000000000000000e-001;
  /* #26: @5 = (@5*@2) */
  w5 *= w2;
  /* #27: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #28: @0 = (@0*@5) */
  w0 *= w5;
  /* #29: @0 = (@0/@3) */
  w0 /= w3;
  /* #30: @4 = (@4+@0) */
  w4 += w0;
  /* #31: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #32: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #33: output[0][2] = @4 */
  if (res[0]) res[0][2] = w4;
  /* #34: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #35: output[0][4] = @2 */
  if (res[0]) res[0][4] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void Spatialbicycle_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Spatialbicycle_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real Spatialbicycle_model_constr_h_fun_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Spatialbicycle_model_constr_h_fun_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Spatialbicycle_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Spatialbicycle_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 6;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
